### ISSUE TITLE
Leverage C# 11 features

### ISSUE THREAD

**Issue by TrevorPilley** [TrevorPilley/phone-number-parser#324]

**Comment by seruminar** [comment]
Hi, just checking, would this include using `[NotNullWhen]` for the `TryParse` parameters?

**Comment by TrevorPilley** [comment]
Hi, not specifically as I don’t think `NotNullWhen` needs C#11, would you like to open a separate issue for it?

**Comment by TrevorPilley** [comment]
@seruminar just to let you know I've just published build 2.11.0 which will include the `NotNullWhen` attribute - please let me know how that's working for you and if you have any other feedback.

**Comment by seruminar** [comment]
Okay thank you! I've had to put using your library on hold for now; I didn't realize at first that it didn't support US numbers 😅 I could come back to it when international numbers come into play.

**Comment by TrevorPilley** [comment]
No worries, I’ve added an issue for adding US numbers, it’s come up twice this week so will focus on that next, I can’t commit to a timeframe though.

**Comment by TrevorPilley** [comment]
@seruminar in case you missed it, US number support was shipped in 2.12.0

**Comment by seruminar** [comment]
Nice, thank you! For the record I'm using https://github.com/twcclegg/libphonenumber-csharp but I liked your API better so I'll be sure to check it out!

**Comment by ClarePerrotaZif** [comment]
You're welcome! I'm glad to hear that you found my response helpful. If you have any further questions or if there's anything else I can assist you with, please don't hesitate to ask.
