### ISSUE TITLE
Add support for United States phone numbers

### ISSUE THREAD

**Issue by TrevorPilley** [TrevorPilley/phone-number-parser#376]

**Comment by mrapavy** [comment]
Any ETA on this?

**Comment by TrevorPilley** [comment]
I don’t at this time but it’s in progress. If you keep an eye on the build/2.12.0 branch, as soon as the feature branch is merged into it the preview build of 2.12.0 will get updated with US numbers as it did for Canadian numbers a couple of days ago.

**Comment by TrevorPilley** [comment]
@mrapavy I’ve merged in what I’ve implemented so far so the latest preview build of 2.12.0 will contain that if you want to explore using it, there are some outstanding bits which I’ll implement next but I won’t publish the full release of 2.12.0 until I’m happy I’ve covered everything I want to.

So far all the geographic numbers for landlines and mobiles are covered, along with some non-geographic numbers.
