### ISSUE TITLE
Namespace and class 'PhoneNumber' conflict with popular Google library: libphonenumber

### ISSUE THREAD

**Issue by jeffward01** [TrevorPilley/phone-number-parser#381]
I was forced to fork `phone-number-parser` and create a new private version of it under a different namespace due to the conflict.  

* [libphonenumber-csharp](https://github.com/twcclegg/libphonenumber-csharp/blob/main/csharp/PhoneNumbers/Phonenumber.cs) (C# port of popular Google library)
   * Namespace: `PhoneNumbers`
   * Class name: `PhoneNumber`

* [Phone-Number-Parser ](https://github.com/TrevorPilley/phone-number-parser/blob/main/src/PhoneNumbers/PhoneNumber.cs)(this library)
   * Namespace: `PhoneNumbers`
   * Class name: `PhoneNumber`

This is an issue that cannot be fixed with 'aliases' or 'global aliases'.  an Alias will fix the issue if it was **only** a namespace or class name conflict, in this case, it is both.  Therefore, these two libraries cannot be used together in the same assembly (`.dll`)

**Comment by TrevorPilley** [comment]
What’s the use case you have which is requiring you to use both libraries in the same project?

**Comment by jeffward01** [comment]
**Use-case**

I believe I use `phone-number-parser` to parse the number and get the ISO-3166 country code.  Then I pass the country code and phone number to the `libphonenumber-csharp`.


**Details**

I know that technically speaking, `phone-number-parser` has all of the same 'main' features. But at some point in the future I will need to work with 'smsShortNumbers', as you type formatting, and a few other esoteric features that are offered by `libphonenumber-csharp`.

I think that `phone-number-parser` is easier to work with, and I prefer this library, but I also don't want to miss out on some features that I might need in the future offered by `lib-phonenumber-csharp`

**Comment by TrevorPilley** [comment]
Ok, interesting to hear how you’re using both and happy to hear you find this one easier to use 😃!

I’m not sure if you are asking if I’ll change my namespace (which I don’t know if I’d want to do) or just pointing out the clash (which is unlikely to affect most users)?

I’m assuming the fork & bespoke build isn’t ideal for you but given your use case would it be easier for you to ‘proxy’ my library in a separate project that just returns the `CountryInfo` or the ISO code so you could still use the nuget version of both libraries and have an easier time keeping up to date?
