### ISSUE TITLE
AU Number Validation - 0493 776 XXX not valid.

### ISSUE THREAD

**Issue by dalechesterfuse** [TrevorPilley/phone-number-parser#536]
The number is passing validation at https://libphonenumber.appspot.com/ but not passing validation using phone-number-parser 3.2.2

This appears to apply for all 0490 7XX XXX numbers

**Comment by TrevorPilley** [comment]
Hi Dale, I notice you’ve closed this but what led you to think it wasn’t initially? Is there something that could be improved with the documentation?
