### ISSUE TITLE
Issue with Parsing US Number

### ISSUE THREAD

**Issue by robjakedorsett** [TrevorPilley/phone-number-parser#551]
Hi, I've just updated to the latest (3.2.4) from (2.12.1), and my unit tests are failing.
Particularily when trying to validate US numbers: i.e. 

- +11234567890
- +1 123-456-7890
- +1 (123) 456-7890
- 123 456 7890

```
	private IEnumerable<string> GetValidatedPhoneNumbers(List<string> phoneNumbers)
	{
		var validatedNumbers = new List<string>();

		foreach (var phoneNumber in phoneNumbers)
		{
			if (PhoneNumber.TryParse(phoneNumber, out PhoneNumber number))
				validatedNumbers.Add(number.ToString());
			else if (PhoneNumber.TryParse(phoneNumber, out IEnumerable<PhoneNumber> numbers))
			{
			    foreach (var number2 in numbers?.Select(x => x.ToString()))
			    {
				    validatedNumbers.Add(number2.ToString());
			    }
			}
		}

		return validatedNumbers;
	}
```

In this example, `validatedNumbers` returns a list containing: "+4311234567890" & "+38111234567890"

**Comment by TrevorPilley** [comment]
Hi, there’s been quite a few changes between those revisions, if it’s not too difficult are you able to pinpoint the actual release that things start failing?

**Comment by robjakedorsett** [comment]
Great - Thanks @TrevorPilley 
I will check in the morning, apologies, been held up on other things, really appreciate the quick turn around!

**Comment by TrevorPilley** [comment]
Hi @robjakedorsett did you get a chance to check this?

**Comment by robjakedorsett** [comment]
Yes, resolved - thanks for the speedy turn around @TrevorPilley
