### ISSUE TITLE
Update German Mobile Phone Numbers

### ISSUE THREAD

**Issue by shriek1** [TrevorPilley/phone-number-parser#687]
So I've been using this for a bit a found that it didn't parse certain mobile phone numbers.
By looking through the defenitions it looks like one area code was added. 

https://de.wikipedia.org/wiki/Deutscher_Mobilfunkmarkt#Netzvorwahlen

The one that seems to be missing is "015566". For example "015566123456".

Can this be added? Or is it maybe a typo as I'm not sure numbers with "015555" exist for mobile phone numbers.

Thanks

**Comment by TrevorPilley** [comment]
Hi, thanks for highlighting this, I’m in the process of updating all the number references as you may have noticed in the last few patch releases, so I’ll prioritise Germany next.

**Comment by shriek1** [comment]
> Hi, thanks for highlighting this, I’m in the process of updating all the number references as you may have noticed in the last few patch releases, so I’ll prioritise Germany next.

Thanks for looking into this. I currently have another issue that I'm looking into still. I can open another issue for that if you like.
The gist is that seems there are certain numbers that have extension numbers that have three digits and are to long to be parsed. If i delete the last digit it works but obviously that is not a solution.

**Comment by TrevorPilley** [comment]
Please file a separate issue for that, however please note that the library doesn’t support extension numbers however they may be ignored if separated from the main number in the input (e.g. `tel:+44-114-272-6444;1234` will successfully parse and ignore everything after the `;`)

**Comment by TrevorPilley** [comment]
I had a bit of time so I’ve fixed this morning in 3.5.5 which should be available via nuget.org within the next few minutes.
