### ISSUE TITLE
TryParse throws exception

### ISSUE THREAD

**Issue by sommmen** [TrevorPilley/phone-number-parser#705]
Hiya, given some invalid data the `TryParse` seems to fault which  shouldn't be the case:

![image](https://github.com/user-attachments/assets/ff527a95-c3c1-40be-a952-655b06567ab6)

``` csharp
PhoneNumbers.PhoneNumber.TryParse(value, country, out var phoneNumber))
```

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Specified argument was out of the range of valid values.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at PhoneNumbers.CountryInfo.ReadNationalSignificantNumber(String value, Int32 startPos)
   at PhoneNumbers.Parsers.PhoneNumberParser.Parse(String value)
   at PhoneNumbers.PhoneNumber.TryParse(String value, CountryInfo countryInfo, ParseOptions options, PhoneNumber& phoneNumber)
   at [REDACTED].NormalizationHelper.PhoneNumber(String value, String country) in [REDACTED]\NormalizationHelper.cs:line 16
```

For values like `---` or `+61`

**Comment by TrevorPilley** [comment]
That’s strange, what version of the library are you using?

**Comment by sommmen** [comment]
> That’s strange, what version of the library are you using?

Latest - i think your recent version broke it but i cant spot the change;

https://github.com/TrevorPilley/phone-number-parser/commit/5964b10d90e7ea94da7f9e35de5df57391c55731#diff-e6ebcd996734656852e898263576bd70afb567bad0809acb570a1f8a4c26dc30

I downgraded to 3.5.5 from 3.5.6 and it works again.

**Comment by TrevorPilley** [comment]
Sorry about that! Fortunately I’ve figured out the problem quite quickly, it was broken in 3.5.6 as a result of the change I made to ignore the extension number in some old German formats. I’ve got a fix building at the moment and will publish 3.5.7 shortly.

**Comment by sommmen** [comment]
The country being Germany should've been the hint haha. Thanks for the fix!
