### ISSUE TITLE
Can't parse phone number for Luxembourg

### ISSUE THREAD

**Issue by shriek1** [TrevorPilley/phone-number-parser#718]
For example the number "(+352) 72 72 33 1" or "(+352) 26 84 60 1" doesn't work at all. Got that from here: http://www.fidest.lu/

Looking at the data files I think the file needs to be extented.
The only thing i could find was an article on wikipedia that lists the area codes (even though they don't really have an area code in luxembourg) that seems to there needing to be more numbers.
[Telephone numbers in Luxembourg](https://en.wikipedia.org/wiki/Telephone_numbers_in_Luxembourg#Areas)

**Comment by TrevorPilley** [comment]
Hi @shriek1, thanks for highlighting this!

I’ve had a look, the ‘72 72 33 1’ number was a typo my side as I was only catering for numbers starting ‘70’ which was incorrect upon re-reading [E.164 Number Ranges in use in Luxembourg](https://assets.ilr.lu/telecom/Documents/ILRLU-1461723625-905.pdf).

Curiously though, the ‘26 84 60 1’ number on the website you referenced appears to be invalid based upon the numbering plan as numbers starting 26 are only 8 digits in length so I’m not sure what to do about that.

**Comment by TrevorPilley** [comment]
I’ve also found a prior version of [E.164 Number Ranges in use in Luxembourg](https://assets.ilr.lu/telecom/Documents/ILRLU-1461723625-633.pdf) from 2017 (the one in the previous post is dated 2021 and linked from the main page https://web.ilr.lu/FR/Professionnels/Communications-electroniques/Numerotation/Numbering-Information-for-international-carriers and also states numbers starting `26` are exactly *8* digits in length.

**Comment by shriek1** [comment]
Nice! The first number was actually the one a user had trouble entering. I just looked up the company for the number and saw the second number and noticed it doesn't work either.
I can try and ask if the know if the second number is somehow different or not. They are local so they might know.

**Comment by TrevorPilley** [comment]
Great, thanks!

I suspect when they evolved the numbering plan and dropped the area codes some older schemes had varying number lengths (as some still have 4-11 digits) and I wonder if some legacy numbers may have been retained but not be 8 digits and the published plan doesn’t indicate that somehow.

**Comment by shriek1** [comment]
Did some searching myself, and some numbers seem to match that file while others totally don't match.
Found some random number [here](http://www.fidest.lu/mmp/online/website/content/contact/contact_map_lux/index_FR.html) (all the way at the bottom of that page) for example that seems to have only five digits and one to three digits for the extension.

Also still waiting on the user to maybe know what's up.

**Comment by TrevorPilley** [comment]
OK, I can consider relax the number ranges where we can clearly see `26` numbers being 7 digits rather than the expected 8 based upon the numbering plan, let me know.

**Comment by shriek1** [comment]
Meh, just noticed I messed up on the link.
https://www.bertrange.lu/

Tél : +352 26 312 - 1

Fax Secrétariat : 26 312 757

Fax Recette : 26 312 355

Fax Service technique : 26 312 666

Fax Etat Civil, Population,
Service Enseignement : 26 312 555

Also found the PDF from 2021 and that is still linked on the official page. So no idea why it isn't like it says there.

**Comment by TrevorPilley** [comment]
No worries, what I’ve done is added support for numbers starting `26` to be 5, 6 or 7 digits in addition to 8 based upon the examples you’ve provided. Keep an eye out for version 3.7.1 of the library which I will contain that update.

Hopefully that covers the ones you’ve found, but anything else you notice please raise an issue 😃
